@startuml

title __TEST's Class Diagram__\n

  package  {
    class FarmSimulatorTest {
        - bulkTankClassRef : ClassRef<S>
        - bulkTankGetTilavuusMethodRef : MethodRef0<S, Double>
        - bulkTankGetSaldoMethodRef : MethodRef0<S, Double>
        - bulkTankPaljonkoTilaaJaljellaMethodRef : MethodRef0<S, Double>
        - bulkTankLisaaSailioonMethodRef : MethodRef1<S, Void, Double>
        - bulkTankOtaSailiostaMethodRef : MethodRef1<S, Double, Double>
        - cowClassRef : ClassRef<L>
        - cowGetNimiMethodRef : MethodRef0<L, String>
        - cowGetTilavuusMethodRef : MethodRef0<L, Double>
        - cowGetMaaraMethodRef : MethodRef0<L, Double>
        - cowLypsaMethodRef : MethodRef0<L, Double>
        - cowEleleTuntiMethodRef : MethodRef0<L, Void>
        - lypsyrobottiClassRef : ClassRef<R>
        - lypsyrobottiLypsaMethodRef : MethodRef1<R, Void, Milkable>
        - lypsyrobottiSetBulkTankMethodRef : MethodRef1<R, Void, S>
        - lypsyrobottiGetBulkTankMethodRef : MethodRef0<R, S>
        - barnClassRef : ClassRef<N>
        - barnGetBulkTankMethodRef : MethodRef0<N, S>
        - barnAsennaMilkingRobotMethodRef : MethodRef1<N, Void, R>
        - barnHoidaCowMethodRef : MethodRef1<N, Void, L>
        - barnHoidaCowtMethodRef : MethodRef1<N, Void, Collection>
        - farmClassRef : ClassRef<M>
        - farmGetOmistajaMethodRef : MethodRef0<M, String>
        - farmAsennaBarnanMilkingRobotMethodRef : MethodRef1<M, Void, R>
        - farmLisaaCowMethodRef : MethodRef1<M, Void, L>
        - farmHoidaCowtMethodRef : MethodRef0<M, Void>
        - farmEleleTuntiMethodRef : MethodRef0<M, Void>
        {static} + testaaOnkoKokonaisLuku()
        + testBulkTank()
        + testCow()
        + testMilkingRobot()
        + testMilkingRobotWithoutTank()
        + testBarn()
        + testFarm()
        - reflektoiBulkTank()
        - luoBulkTank()
        - testaaTilavuus()
        - testaaSaldo()
        - toString()
        - testaaPaljonkoTilaaJaljella()
        - testaaLisaaSailioon()
        - testaaOtaSailiosta()
        - reflektoiCow()
        - luoCow()
        - testaaCownElelemista()
        - testaaCownElelemista()
        - testaaCownLypsamista()
        - reflektoiMilkingRobot()
        - luoMilkingRobot()
        - testaaLypsyrobotinLypsamistaIlmanSailota()
        - testaaLypsyrobotinLypsamista()
        - reflektoiBarn()
        - luoBarn()
        - laskeMaidonMaaraLehmissa()
        - annaBulkTanknSaldo()
        - annaBulkTanknTilavuus()
        - testaaNavetanLehmienHoitamista()
        - reflektoiFarm()
        - luoFarm()
        - testaaFarmnLehmienHoitamista()
        - saniteettitarkastus()
        - kentta()
        - s()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
